[package]
name = "capybafirmations_commons"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
server = ["sea-orm"]
client = []

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
language-tag = "^0.9"

[dependencies.sea-orm]
version = "^0.5"
features = ["macros"]
optional = true