[workspace]

members = [
    "coconutpak/coconutpak_compiler",
    "coconutpak/coconutpak_island",
    "coconutpak/cocopak",
    "kindkapibari/kindkapibari_core",
    "kindkapibari/kindkapibari_server",
    "kindkapibari/kindkapibari_client",
]