[package]
name = "kindkapybari_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.kindkapibari_core]
path = "../kindkapibari_core"
default-features = false